server {
    listen 80;
    server_name bullwebchile.com www.bullwebchile.com;
    return 301 https://www.bullwebchile.com$request_uri;
}

server {
    listen 443 ssl http2;
    server_name bullwebchile.com;
    ssl_certificate     /etc/letsencrypt/live/bullwebchile.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bullwebchile.com/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;
    return 301 https://www.bullwebchile.com$request_uri;
}

server {
    listen 443 ssl http2;
    server_name www.bullwebchile.com;

    ssl_certificate     /etc/letsencrypt/live/bullwebchile.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bullwebchile.com/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

    root  /var/www/bullweb-landing;
    index index.html;

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
        access_log off;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
}
